-- CreateEnum
CREATE TYPE "ImageSetStatus" AS ENUM ('DRAFT', 'SENT', 'ARCHIVED', 'DELETED');

-- CreateEnum
CREATE TYPE "AttachmentRecordType" AS ENUM ('USER', 'IMAGE_SET');

-- CreateTable
CREATE TABLE "am_users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "email" STRING NOT NULL,
    "name" STRING,
    "seqId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "am_users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dm_image_sets" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" STRING,
    "ownerId" UUID,
    "status" "ImageSetStatus" NOT NULL DEFAULT 'DRAFT',
    "seqId" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "dm_image_sets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dm_files" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "key" STRING NOT NULL,
    "filename" STRING NOT NULL,
    "contentType" STRING NOT NULL,
    "size" INT4 NOT NULL,
    "version" INT4 NOT NULL DEFAULT 1,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "dm_files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dm_file_attachments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "recordType" "AttachmentRecordType" NOT NULL,
    "recordId" STRING NOT NULL,
    "name" STRING NOT NULL,
    "fileId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "dm_file_attachments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "am_users_email_key" ON "am_users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "am_users_seqId_key" ON "am_users"("seqId");

-- CreateIndex
CREATE UNIQUE INDEX "dm_image_sets_seqId_key" ON "dm_image_sets"("seqId");

-- CreateIndex
CREATE INDEX "dm_image_sets_ownerId_idx" ON "dm_image_sets"("ownerId");

-- CreateIndex
CREATE UNIQUE INDEX "dm_files_key_key" ON "dm_files"("key");

-- CreateIndex
CREATE INDEX "dm_files_key_idx" ON "dm_files"("key");

-- CreateIndex
CREATE INDEX "dm_file_attachments_fileId_idx" ON "dm_file_attachments"("fileId");

-- CreateIndex
CREATE INDEX "dm_file_attachments_recordType_recordId_idx" ON "dm_file_attachments"("recordType", "recordId");

-- AddForeignKey
ALTER TABLE "dm_image_sets" ADD CONSTRAINT "dm_image_sets_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "am_users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dm_file_attachments" ADD CONSTRAINT "dm_file_attachments_fileId_fkey" FOREIGN KEY ("fileId") REFERENCES "dm_files"("id") ON DELETE CASCADE ON UPDATE CASCADE;
